services:
  - type: web
    name: artee-backend
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/artee-group.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-rapid-thunder-a175uiqx-pooler.ap-southeast-1.aws.neon.tech/artee-be?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: artee-be_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_pnTezm4CBPq9
